// <auto-generated />
using LinqSamples.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LinqSamples.Migrations
{
    [DbContext(typeof(AvengersDb))]
    [Migration("20190521184225_InitialSetup")]
    partial class InitialSetup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("LinqSamples.Models.Avenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Codename")
                        .IsRequired();

                    b.Property<string>("MainSkill");

                    b.HasKey("Id");

                    b.ToTable("Avengers");
                });
#pragma warning restore 612, 618
        }
    }
}
